# Generated by Django 5.0.4 on 2024-12-12 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentintent",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="paymentintent",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="paymentintent",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="paymentintent",
            name="session_id",
        ),
        migrations.RemoveField(
            model_name="paymentintent",
            name="status",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="wompi_id",
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="payment_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.transaction",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_intent_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=10,
                null=True,
            ),
        ),
    ]
