# Generated by Django 5.0.4 on 2024-12-19 17:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_remove_paymentintent_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="id",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="payment_intent_id",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="transaction",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.DeleteModel(
            name="PaymentIntent",
        ),
    ]
