# Generated by Django 5.0.4 on 2024-12-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_remove_transaction_currency_remove_transaction_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("DECLINED", "Declined"),
                    ("VOIDED", "Voided"),
                    ("ERROR", "Error"),
                ],
                default="PENDING",
                max_length=10,
                null=True,
            ),
        ),
    ]
