# Generated by Django 5.0.4 on 2024-12-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_transaction_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="wompi_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
