# Generated by Django 5.0.4 on 2025-02-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_transaction_wompi_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
