# Generated by Django 5.0.4 on 2025-02-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_transaction_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
