# Generated by Django 5.0.4 on 2024-12-28 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Organizer",
                "verbose_name_plural": "Organizers",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="event",
            name="available_tickets",
        ),
        migrations.RemoveField(
            model_name="event",
            name="is_cancelled",
        ),
        migrations.RemoveField(
            model_name="event",
            name="original_ticket_price_range",
        ),
        migrations.RemoveField(
            model_name="eventcategory",
            name="description",
        ),
        migrations.AddField(
            model_name="venue",
            name="address",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="events.eventcategory",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(default="", max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.venue",
                verbose_name="Lugar del evento",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="events.organizer",
                verbose_name="Organizador",
            ),
        ),
    ]
