# Generated by Django 5.0.4 on 2024-12-28 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_organizer_remove_event_available_tickets_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["date"], "verbose_name": "Event"},
        ),
        migrations.AlterModelOptions(
            name="organizer",
            options={"ordering": ["name"], "verbose_name": "Organizer"},
        ),
        migrations.AlterModelOptions(
            name="venue",
            options={"ordering": ["name"], "verbose_name": "Venue"},
        ),
    ]
