# Generated by Django 5.0.4 on 2024-12-28 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_options_alter_organizer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="events.eventcategory",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="events.organizer",
                verbose_name="Organizador",
            ),
        ),
    ]
