# Generated by Django 5.0.4 on 2025-02-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_category_alter_event_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["start_datetime"], "verbose_name": "Event"},
        ),
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        migrations.AddField(
            model_name="event",
            name="end_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha y hora de finalización"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="start_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha y hora de inicio"
            ),
        ),
    ]
