# Generated by Django 5.0.4 on 2025-02-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_options_remove_event_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_datetime",
            field=models.DateTimeField(
                default="2025-03-15 12:34:56",
                verbose_name="Fecha y hora de finalización",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="start_datetime",
            field=models.DateTimeField(
                default="2025-04-15 12:34:56", verbose_name="Fecha y hora de inicio"
            ),
            preserve_default=False,
        ),
    ]
