# Generated by Django 5.0.4 on 2025-02-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_event_end_datetime_alter_event_start_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="latitude",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="longitude",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
