# Generated by Django 5.0.4 on 2025-03-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_venue_latitude_venue_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
