version: '3.8'

services:
  django_app:
    build:
      context: .
    depends_on:
      - db
      - mailhog
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: revendelauser
      POSTGRES_PASSWORD: revendela123
      POSTGRES_DB: revendeladb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  
      - "8025:8025"  

volumes:
  postgres_data:
