version: '3.8'
services:
  django_app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: revendelauser
      POSTGRES_PASSWORD: revendela123
      POSTGRES_DB: revendeladb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
