# Generated by Django 5.0.4 on 2025-01-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("buyer", "Buyer"), ("seller", "Seller")],
                default="buyer",
                help_text="Role of the user: buyer or seller.",
                max_length=10,
            ),
        ),
    ]
