# Generated by Django 5.0.4 on 2025-01-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authy", "0002_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("buyer", "Buyer"), ("seller", "Seller")],
                default="buyer",
                max_length=10,
            ),
        ),
    ]
