# Generated by Django 5.0.4 on 2025-01-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authy", "0003_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("buyer", "Buyer"), ("seller", "Seller")], max_length=10
            ),
        ),
    ]
