# Generated by Django 5.0.4 on 2025-01-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authy", "0004_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("buyer", "Comprador"), ("seller", "Vendedor")], max_length=10
            ),
        ),
    ]
