# Generated by Django 5.0.4 on 2025-01-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_alter_ticket_event_alter_ticket_seller_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="purchase_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AVAILABLE", "Disponible"),
                    ("PENDING", "Pendiente"),
                    ("SOLD", "Vendido"),
                ],
                default="AVAILABLE",
                max_length=10,
                null=True,
            ),
        ),
    ]
