# Generated by Django 5.0.4 on 2024-12-28 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_options_alter_organizer_options_and_more"),
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="purchase_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AVAILABLE", "Available"),
                    ("PENDING", "Pending"),
                    ("SOLD", "Sold"),
                ],
                default="AVAILABLE",
                max_length=10,
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="number",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="original_purchase_info",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="row",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="seat_section",
        ),
        migrations.AddField(
            model_name="ticket",
            name="venue_location",
            field=models.CharField(default="", max_length=100, verbose_name="Locacion"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="event",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Evento",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seller",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Vendedor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="PurchaseStatus",
        ),
    ]
