# Generated by Django 5.0.4 on 2024-12-28 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_category_alter_event_name_and_more"),
        ("tickets", "0002_alter_ticket_purchase_status_remove_ticket_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Evento",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Vendedor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="venue_location",
            field=models.CharField(max_length=100, verbose_name="Locacion"),
        ),
    ]
