# Generated by Django 5.0.4 on 2025-02-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_alter_ticket_purchase_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="purchase_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AVAILABLE", "Disponible"),
                    ("PENDING", "Pendiente"),
                    ("SOLD", "Vendido"),
                    ("SENT", "Enviado"),
                    ("CLOSED", "Cerrado"),
                ],
                default="AVAILABLE",
                max_length=10,
                null=True,
            ),
        ),
    ]
