# Generated by Django 5.0.4 on 2025-02-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_alter_ticket_purchase_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="resale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Precio de reventa",
            ),
        ),
    ]
