# Generated by Django 5.0.4 on 2025-02-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_alter_ticket_resale_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="last_status_change",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Último cambio de estado"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="purchase_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AVAILABLE", "Disponible"),
                    ("PENDING", "Pendiente"),
                    ("SOLD", "Vendido"),
                    ("SENT", "Enviado"),
                    ("CLOSED", "Cerrado"),
                    ("CANCELLED_SELLER", "Cancelado"),
                ],
                default="AVAILABLE",
                max_length=20,
                null=True,
            ),
        ),
    ]
