# Generated by Django 5.0.4 on 2025-02-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_ticket_last_status_change_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="last_status_change",
            field=models.DateTimeField(verbose_name="Último cambio de estado"),
        ),
    ]
