# Generated by Django 5.0.4 on 2025-02-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0010_ticket_created_time_alter_ticket_last_status_change"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="last_status_change",
            field=models.DateTimeField(verbose_name="Último cambio de estado"),
        ),
    ]
