# Generated by Django 5.0.4 on 2025-02-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0011_alter_ticket_last_status_change"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="purchase_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AVAILABLE", "Disponible"),
                    ("PENDING", "Pendiente"),
                    ("SOLD", "Vendido"),
                    ("SENT", "Enviado"),
                    ("CLOSED", "Cerrado"),
                    ("CANCELLED_SELLER", "Cancelado"),
                    ("CANCELLED_EVENT_TIME", "Cancelado por finalizacion del evento"),
                ],
                default="AVAILABLE",
                max_length=20,
                null=True,
            ),
        ),
    ]
