name: CI/CD Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: revendela
          POSTGRES_USER: revendelauser
          POSTGRES_PASSWORD: revendela123
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U revendelauser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_NAME: revendela
      DATABASE_USER: revendelauser
      DATABASE_PASSWORD: revendela123
      DATABASE_HOST: 127.0.0.1  
      DATABASE_PORT: 5432

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4  

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
        continue-on-error: true

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
        continue-on-error: true

      - name: Aplicar migraciones
        run: |
          python manage.py migrate

      - name: Ejecutar pruebas
        run: pytest
