name: CI/CD Pipeline  

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  
    env:
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_HOST: $DATABASE_HOST
      DATABASE_PORT: $DATABASE_PORT
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
      FACEBOOK_APP_ID: $FACEBOOK_APP_ID
      FACEBOOK_SECRET_KEY: $FACEBOOK_SECRET_KEY
      WOMPI_PUBLIC_KEY: $WOMPI_PUBLIC_KEY
      WOMPI_PRIVATE_KEY: $WOMPI_PRIVATE_KEY
      WOMPI_SECRET_KEY: $WOMPI_SECRET_KEY
      WOMPI_BASE_URL: $WOMPI_BASE_URL
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4  

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Ejecutar pruebas
        run: pytest
