name: CI/CD Pipeline  

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4  

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Ejecutar pruebas
        run: pytest
